export const DummyBook = [
  {
    id: "1",
    title: "Book Title 1",
    writer: "Writer 1",
    coverImage: "cover1.jpg",
    price: 55,
    tags: ["science", "essay"],
  },
  {
    id: "2",
    title: "Book Title 2",
    writer: "Writer 2",
    coverImage: "cover1.jpg",
    price: 40,
    tags: ["non-fiction", "science"],
  },
  {
    id: "3",
    title: "Book Title 3",
    writer: "Writer 3",
    coverImage: "cover1.jpg",
    price: 83,
    tags: ["non-fiction", "science"],
  },
  {
    id: "4",
    title: "Book Title 4",
    writer: "Writer 4",
    coverImage: "cover1.jpg",
    price: 21,
    tags: ["non-fiction", "science"],
  },
  {
    id: "5",
    title: "Book Title 5",
    writer: "Writer 5",
    coverImage: "cover1.jpg",
    price: 8,
    tags: ["essay", "non-fiction"],
  },
  {
    id: "6",
    title: "Book Title 6",
    writer: "Writer 6",
    coverImage: "cover1.jpg",
    price: 39,
    tags: ["essay", "non-fiction"],
  },
  {
    id: "7",
    title: "Book Title 7",
    writer: "Writer 7",
    coverImage: "cover1.jpg",
    price: 37,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "8",
    title: "Book Title 8",
    writer: "Writer 8",
    coverImage: "cover1.jpg",
    price: 80,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "9",
    title: "Book Title 9",
    writer: "Writer 9",
    coverImage: "cover1.jpg",
    price: 65,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "10",
    title: "Book Title 10",
    writer: "Writer 10",
    coverImage: "cover1.jpg",
    price: 84,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "11",
    title: "Book Title 11",
    writer: "Writer 11",
    coverImage: "cover1.jpg",
    price: 69,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "12",
    title: "Book Title 12",
    writer: "Writer 12",
    coverImage: "cover1.jpg",
    price: 97,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "13",
    title: "Book Title 13",
    writer: "Writer 13",
    coverImage: "cover1.jpg",
    price: 6,
    tags: ["essay", "non-fiction"],
  },
  {
    id: "14",
    title: "Book Title 14",
    writer: "Writer 14",
    coverImage: "cover1.jpg",
    price: 51,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "15",
    title: "Book Title 15",
    writer: "Writer 15",
    coverImage: "cover1.jpg",
    price: 51,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "16",
    title: "Book Title 16",
    writer: "Writer 16",
    coverImage: "cover1.jpg",
    price: 74,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "17",
    title: "Book Title 17",
    writer: "Writer 17",
    coverImage: "cover1.jpg",
    price: 77,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "18",
    title: "Book Title 18",
    writer: "Writer 18",
    coverImage: "cover1.jpg",
    price: 10,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "19",
    title: "Book Title 19",
    writer: "Writer 19",
    coverImage: "cover1.jpg",
    price: 49,
    tags: ["essay", "non-fiction"],
  },
  {
    id: "20",
    title: "Book Title 20",
    writer: "Writer 20",
    coverImage: "cover1.jpg",
    price: 62,
    tags: ["fiction", "novel", "science"],
  },
  {
    id: "21",
    title: "Book 21",
    writer: "Writer 21\n",
    coverImage: "cover1.jpg",
    price: 0,
    tags: ["essay", "non-fiction"],
  },
];
