export const DummyBook = [
  {
    id: "1",
    title: "Course Title 1",
    instructor: "Instructor 1",
    coverImage: "cover1.jpg",
    price: 55,
    tags: ["computer-science", "programming"],
  },
  {
    id: "2",
    title: "Course Title 2",
    instructor: "Instructor 2",
    coverImage: "cover1.jpg",
    price: 40,
    tags: ["software-engineering", "algorithms"],
  },
  {
    id: "3",
    title: "Course Title 3",
    instructor: "Instructor 3",
    coverImage: "cover1.jpg",
    price: 83,
    tags: ["web-development", "javascript"],
  },
  {
    id: "4",
    title: "Course Title 4",
    instructor: "Instructor 4",
    coverImage: "cover1.jpg",
    price: 21,
    tags: ["data-structures", "python"],
  },
  {
    id: "5",
    title: "Course Title 5",
    instructor: "Instructor 5",
    coverImage: "cover1.jpg",
    price: 8,
    tags: ["java", "object-oriented-programming"],
  },
  {
    id: "6",
    title: "Course Title 6",
    instructor: "Instructor 6",
    coverImage: "cover1.jpg",
    price: 39,
    tags: ["frontend-development", "react"],
  },
  {
    id: "7",
    title: "Course Title 7",
    instructor: "Instructor 7",
    coverImage: "cover1.jpg",
    price: 37,
    tags: ["backend-development", "nodejs"],
  },
  {
    id: "8",
    title: "Course Title 8",
    instructor: "Instructor 8",
    coverImage: "cover1.jpg",
    price: 80,
    tags: ["software-development", "git"],
  },
  {
    id: "9",
    title: "Course Title 9",
    instructor: "Instructor 9",
    coverImage: "cover1.jpg",
    price: 65,
    tags: ["database-management", "sql"],
  },
  {
    id: "10",
    title: "Course Title 10",
    instructor: "Instructor 10",
    coverImage: "cover1.jpg",
    price: 84,
    tags: ["cloud-computing", "aws"],
  },
  {
    id: "11",
    title: "Course Title 11",
    instructor: "Instructor 11",
    coverImage: "cover1.jpg",
    price: 69,
    tags: ["cybersecurity", "ethical-hacking"],
  },
  {
    id: "12",
    title: "Course Title 12",
    instructor: "Instructor 12",
    coverImage: "cover1.jpg",
    price: 97,
    tags: ["data-science", "machine-learning"],
  },
  {
    id: "13",
    title: "Course Title 13",
    instructor: "Instructor 13",
    coverImage: "cover1.jpg",
    price: 6,
    tags: ["coding-interview", "algorithm-analysis"],
  },
  {
    id: "14",
    title: "Course Title 14",
    instructor: "Instructor 14",
    coverImage: "cover1.jpg",
    price: 51,
    tags: ["software-testing", "quality-assurance"],
  },
  {
    id: "15",
    title: "Course Title 15",
    instructor: "Instructor 15",
    coverImage: "cover1.jpg",
    price: 51,
    tags: ["devops", "continuous-integration"],
  },
  {
    id: "16",
    title: "Course Title 16",
    instructor: "Instructor 16",
    coverImage: "cover1.jpg",
    price: 74,
    tags: ["full-stack-development", "mongodb"],
  },
  {
    id: "17",
    title: "Course Title 17",
    instructor: "Instructor 17",
    coverImage: "cover1.jpg",
    price: 77,
    tags: ["frontend-design", "css"],
  },
  {
    id: "18",
    title: "Course Title 18",
    instructor: "Instructor 18",
    coverImage: "cover1.jpg",
    price: 10,
    tags: ["backend-architecture", "rest-api"],
  },
  {
    id: "19",
    title: "Course Title 19",
    instructor: "Instructor 19",
    coverImage: "cover1.jpg",
    price: 49,
    tags: ["functional-programming", "haskell"],
  },
  {
    id: "20",
    title: "Course Title 20",
    instructor: "Instructor 20",
    coverImage: "cover1.jpg",
    price: 62,
    tags: ["embedded-systems", "arduino"],
  },
  {
    id: "21",
    title: "Course Title 21",
    instructor: "Instructor 21",
    coverImage: "cover1.jpg",
    price: 0,
    tags: ["mobile-development", "flutter"],
  },
];
